#
# Copyright (C) 2019 AICP
#
# SPDX-License-Identifier: Apache-2.0
#

# Init (Android project name autogenerated by vendor_buildinfo.sh as a system.prop)
PRODUCT_PROPERTY_OVERRIDES += \
    ro.boot.project_name=18857 \
    ro.vendor.boot.project_name=18857

# build properties
PRODUCT_PROPERTY_OVERRIDES += \
    persist.sys.oem.region=OverSeas \
    ro.product.device=guacamoleb \
    ro.vendor.build.real.device=true \
    vendor.product.device=guacamoleb \
    vendor.product.manufacturer=OPD

# Netflix custom property
PRODUCT_PROPERTY_OVERRIDES += \
    ro.netflix.bsp_rev=Q845-05000-1
